name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Linter
    uses: samjuk/github-actions/.github/workflows/magento2-test-lint.yaml@master

  static:
    name: Static Analysis
    uses: samjuk/github-actions/.github/workflows/magento2-test-static.yaml@master
    needs: lint

  supported-versions:
    name: Supported Versions
    uses: samjuk/github-actions/.github/workflows/magento-supported-versions.yaml@master

  phpunit-tests-ghas:
    name: PHPUnit Tests (GHAS)
    uses: samjuk/github-actions/.github/workflows/magento2-test-phpunit-module-ghas.yaml@master
    needs: [static, supported-versions]
    with:
      magento_version: ${{ matrix.version }}
      magento_distribution: ${{ matrix.distribution }}
      run_unit_tests: true
      run_integration_tests: true
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.supported-versions.outputs.versions) }}
